// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixrguufqdgzitsgdtawl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4cmd1dWZxZGd6aXRzZ2R0YXdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTkwNTMsImV4cCI6MjA3NDE5NTA1M30.SY5emx5x9Vjk0orcwFxD-vOciOySRkNAqTV-ktEW-Tw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});